openapi: 3.0.3
info:
  title: REST API для социальной сети ВКонтакте
  version: 1.0.0
servers:
  - url: https://vk.com/api/v1
paths:
  /friends:
    get:
      tags:
        - Friends
      summary: Просмотр друзей текущего пользователя
      security:
        - oAuthSample:
            - friends
    post:
      tags:
        - Friends
      summary: Добавление пользователя в друзья
      security:
        - oAuthSample:
            - friends
  /friends/{userId}:
    get:
      tags:
        - Friends
      summary: Просмотр друзей других пользователей
      security:
        - oAuthSample:
            - friends
    delete:
      tags:
        - Friends
      summary: Удаление пользователя из друзей
  /profile:
    get:
      tags:
        - Profile
      summary: Просмотр анкеты текущего пользователя
      security:
        - oAuthSample:
            - profiles
  /profile/{userId}:
    get:
      tags:
        - Profile
      summary: Просмотр анкеты других пользователей
      security:
        - oAuthSample:
            - profiles
  /posts:
    get:
      tags:
        - Posts
      summary: Просмотр ленты постов текущего пользователя
      security:
        - oAuthSample:
            - posts
    post:
      tags:
        - Posts
      summary: Публикация поста в ленту текущего пользователя
      security:
        - oAuthSample:
            - posts
  /posts/{userId}:
    get:
      tags:
        - Posts
      summary: Просмотр ленты постов других пользователей
      security:
        - oAuthSample:
            - posts
    post:
      tags:
        - Posts
      summary: Публикация поста в ленту других пользователей
      security:
        - oAuthSample:
            - posts
  /posts/{postId}/attachments:
    post:
      tags:
        - Posts
      summary: Загрузка медиа файлов для постов
      security:
        - oAuthSample:
            - posts
  /conversations:
    get:
      tags:
        - Conversations
      summary: Просмотр диалогов и чатов пользователя
      security:
        - oAuthSample:
            - conversations
  /conversations/{conversationId}:
    get:
      tags:
        - Conversations
      summary: Чтение сообщений в диалогах и чатах
      security:
        - oAuthSample:
            - conversations
    post:
      tags:
        - Conversations
      summary: Отправка сообщений в диалогах и чатах
      security:
        - oAuthSample:
            - conversations

components:
  securitySchemes:
    oAuthSample:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        implicit:
          authorizationUrl: https://oauth.vk.com/oauth2/authorize
          scopes:
            profiles: profiles
            friends: friends
            posts: posts
            conversations: conversations
