openapi: 3.0.3
info:
  title: REST API for social networks VK
  version: 1.0.0
servers:
  - url: https://vk.com/api/v1
paths:
  /friends:
    get:
      tags:
        - Friends
      summary: View current user's friends
      security:
        - oAuthSample:
            - friends
    post:
      tags:
        - Friends
      summary: Adding a user as a friend
      security:
        - oAuthSample:
            - friends
  /friends/{userId}:
    get:
      tags:
        - Friends
      summary: View friends of other users
      security:
        - oAuthSample:
            - friends
    delete:
      tags:
        - Friends
      summary: Removing a user from friends
  /profile:
    get:
      tags:
        - Profile
      summary: Viewing the profile of the current user
      security:
        - oAuthSample:
            - profiles
  /profile/{userId}:
    get:
      tags:
        - Profile
      summary: View profile of other users
      security:
        - oAuthSample:
            - profiles
  /posts:
    get:
      tags:
        - Posts
      summary: View the feed of the current user's posts
      security:
        - oAuthSample:
            - posts
    post:
      tags:
        - Posts
      summary: Publishing a post to the current user's feed
      security:
        - oAuthSample:
            - posts
  /posts/{userId}:
    get:
      tags:
        - Posts
      summary: View the feed of other users' posts
      security:
        - oAuthSample:
            - posts
    post:
      tags:
        - Posts
      summary: Publishing a post to the feed of other users
      security:
        - oAuthSample:
            - posts
  /posts/{postId}/attachments:
    post:
      tags:
        - Posts
      summary: Uploading media files for posts
      security:
        - oAuthSample:
            - posts
  /conversations:
    get:
      tags:
        - Conversations
      summary: View user dialogs and chats
      security:
        - oAuthSample:
            - conversations
  /conversations/{conversationId}:
    get:
      tags:
        - Conversations
      summary: Reading messages in dialogs and chats
      security:
        - oAuthSample:
            - conversations
    post:
      tags:
        - Conversations
      summary: Sending messages in dialogs and chats
      security:
        - oAuthSample:
            - conversations

components:
  securitySchemes:
    oAuthSample:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        implicit:
          authorizationUrl: https://oauth.vk.com/oauth2/authorize
          scopes:
            profiles: profiles
            friends: friends
            posts: posts
            conversations: conversations
